#!/usr/bin/perl
use 5.016;

my @inp = (split //, shift @ARGV);

die "32 chars only. You now have ".scalar @inp unless scalar @inp == 32;

my @orig = split //,'We go about our daily lives understanding almost nothing of the world. Few of us spend much time wondering why nature is the way it is; where the cosmos came from;... why we remember the past and not the future; and why there is a universe.';

my $ebx;
foreach (@inp){
    $ebx += ord $_;
}

my $bl = ($ebx & 0xff );

my @result;
foreach (@orig){
    my $dl = $bl%32 & 0xff;
    my $crypt = ord($inp[$dl] ^ $_) + $dl ;
    unshift @result, chr($crypt);
    $bl = (ord $crypt) & 0xff;
}

say @result;
